---
- name: ensure postgresql directories
  file:
    path: "{{ item }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0750
  loop:
    - "{{ postgresql_cluster_configuration_directory }}"
    - "{{ postgresql_cluster_data_directory }}"
  become: true
